.OPTION EXPLICIT
.Set CabinetNameTemplate=.\Package_drives.cab
.set DiskDirectoryTemplate=.
.Set CompressionType=MSZIP
.Set MaxCabinetSize=0
.Set MaxDiskFileCount=0
.Set MaxDiskSize=0
.Set UniqueFiles="OFF"
.Set Cabinet=On
.Set DiskDirectory1=E:\PartImage\Ethernet_drv
.Set DestinationDir=""

.Set DestinationDir=".\3com"

.Set DestinationDir=".\3com\lan"
"E:\PartImage\Ethernet_drv\3com\lan\3C99X.dll"
"E:\PartImage\Ethernet_drv\3com\lan\b57xp32.inf"
"E:\PartImage\Ethernet_drv\3com\lan\b57xp32.sys"
"E:\PartImage\Ethernet_drv\3com\lan\EL2000.CAT"
"E:\PartImage\Ethernet_drv\3com\lan\EL2000x.inf"
"E:\PartImage\Ethernet_drv\3com\lan\EL2k_CPP.dll"
"E:\PartImage\Ethernet_drv\3com\lan\EL2K_XP.sys"
"E:\PartImage\Ethernet_drv\3com\lan\EL59X.SYS"
"E:\PartImage\Ethernet_drv\3com\lan\el90xbc5.sys"
"E:\PartImage\Ethernet_drv\3com\lan\el90xnd5.sys"
"E:\PartImage\Ethernet_drv\3com\lan\EL99XN51.sys"
"E:\PartImage\Ethernet_drv\3com\lan\el99xrun.out"
"E:\PartImage\Ethernet_drv\3com\lan\EL99X_NT.cat"
"E:\PartImage\Ethernet_drv\3com\lan\EL99x_NT.inf"
"E:\PartImage\Ethernet_drv\3com\lan\NETEL59X.INF"
"E:\PartImage\Ethernet_drv\3com\lan\readme.txt"
"E:\PartImage\Ethernet_drv\3com\lan\W9X90XBC.INF"
"E:\PartImage\Ethernet_drv\3com\lan\W9XEL90X.INF"

.Set DestinationDir=".\3com\wlan"
"E:\PartImage\Ethernet_drv\3com\wlan\3C154A72.inf"
"E:\PartImage\Ethernet_drv\3com\wlan\3C154A72.SYS"
"E:\PartImage\Ethernet_drv\3com\wlan\3C154G72.INF"
"E:\PartImage\Ethernet_drv\3com\wlan\3C154G72.sys"
"E:\PartImage\Ethernet_drv\3com\wlan\CCU3C154.DLL"
"E:\PartImage\Ethernet_drv\3com\wlan\CCU3C154.EXE"
"E:\PartImage\Ethernet_drv\3com\wlan\CCUA72.dll"
"E:\PartImage\Ethernet_drv\3com\wlan\CCUA72.exe"
"E:\PartImage\Ethernet_drv\3com\wlan\mrv8335x.inf"
"E:\PartImage\Ethernet_drv\3com\wlan\MRV8335XP.sys"
"E:\PartImage\Ethernet_drv\3com\wlan\net5213.inf"
"E:\PartImage\Ethernet_drv\3com\wlan\net5213.sys"
"E:\PartImage\Ethernet_drv\3com\wlan\net5213b.inf"
"E:\PartImage\Ethernet_drv\3com\wlan\net5213xp.sys"
"E:\PartImage\Ethernet_drv\3com\wlan\netwc175.inf"
"E:\PartImage\Ethernet_drv\3com\wlan\netwp92b.inf"
"E:\PartImage\Ethernet_drv\3com\wlan\netwpx96.inf"
"E:\PartImage\Ethernet_drv\3com\wlan\OEMSETUP.INF"
"E:\PartImage\Ethernet_drv\3com\wlan\PRISMNDS.sys"
"E:\PartImage\Ethernet_drv\3com\wlan\readme.txt"
"E:\PartImage\Ethernet_drv\3com\wlan\wlc175f.sys"
"E:\PartImage\Ethernet_drv\3com\wlan\wlp92bf.sys"
"E:\PartImage\Ethernet_drv\3com\wlan\wlpx96f.sys"

.Set DestinationDir=".\amd"
"E:\PartImage\Ethernet_drv\amd\am8111n4.sys"
"E:\PartImage\Ethernet_drv\amd\amddlg.dll"
"E:\PartImage\Ethernet_drv\amd\amddlgn4.dll"
"E:\PartImage\Ethernet_drv\amd\amdl7n5.inf"
"E:\PartImage\Ethernet_drv\amd\amdl7n5.sys"
"E:\PartImage\Ethernet_drv\amd\netamd.inf"
"E:\PartImage\Ethernet_drv\amd\netamdhl.inf"
"E:\PartImage\Ethernet_drv\amd\pcntn5hl.sys"
"E:\PartImage\Ethernet_drv\amd\pcntpci5.sys"

.Set DestinationDir=".\broadcom"

.Set DestinationDir=".\broadcom\lan"
"E:\PartImage\Ethernet_drv\broadcom\lan\readme.txt"

.Set DestinationDir=".\broadcom\lan\1085"
"E:\PartImage\Ethernet_drv\broadcom\lan\1085\b57win32.cat"
"E:\PartImage\Ethernet_drv\broadcom\lan\1085\b57win32.inf"
"E:\PartImage\Ethernet_drv\broadcom\lan\1085\b57xp32.sys"

.Set DestinationDir=".\broadcom\lan\1117"
"E:\PartImage\Ethernet_drv\broadcom\lan\1117\k57win32.cat"
"E:\PartImage\Ethernet_drv\broadcom\lan\1117\k57win32.inf"
"E:\PartImage\Ethernet_drv\broadcom\lan\1117\k57xp32.sys"

.Set DestinationDir=".\broadcom\lan\460"
"E:\PartImage\Ethernet_drv\broadcom\lan\460\b44win.cat"
"E:\PartImage\Ethernet_drv\broadcom\lan\460\b44win.inf"
"E:\PartImage\Ethernet_drv\broadcom\lan\460\bcm4sbxp.sys"

.Set DestinationDir=".\broadcom\lan\634"
"E:\PartImage\Ethernet_drv\broadcom\lan\634\b57xp32.inf"
"E:\PartImage\Ethernet_drv\broadcom\lan\634\b57xp32.sys"

.Set DestinationDir=".\broadcom\lan\743"
"E:\PartImage\Ethernet_drv\broadcom\lan\743\b57xp32.inf"
"E:\PartImage\Ethernet_drv\broadcom\lan\743\b57xp32.sys"

.Set DestinationDir=".\broadcom\wlan"
"E:\PartImage\Ethernet_drv\broadcom\wlan\readme.txt"

.Set DestinationDir=".\broadcom\wlan\Dell"
"E:\PartImage\Ethernet_drv\broadcom\wlan\Dell\BCMWL5.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\Dell\BCMWL5.SYS"

.Set DestinationDir=".\broadcom\wlan\hp"
"E:\PartImage\Ethernet_drv\broadcom\wlan\hp\bcm43xx.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\hp\bcmwl5.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\hp\bcmwl5.sys"
"E:\PartImage\Ethernet_drv\broadcom\wlan\hp\bcmwlcoi.dll"
"E:\PartImage\Ethernet_drv\broadcom\wlan\hp\readme.txt"

.Set DestinationDir=".\broadcom\wlan\lenovo"
"E:\PartImage\Ethernet_drv\broadcom\wlan\lenovo\bcm43xx.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\lenovo\bcmwl5.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\lenovo\bcmwl5.sys"
"E:\PartImage\Ethernet_drv\broadcom\wlan\lenovo\readme.txt"

.Set DestinationDir=".\broadcom\wlan\otr"

.Set DestinationDir=".\broadcom\wlan\otr\3008"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3008\bcm43xx.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3008\bcmwl5.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3008\bcmwl5.sys"

.Set DestinationDir=".\broadcom\wlan\otr\3050"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3050\bcmwl5.sys"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3050\lsbcmnds.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3050\lsbcmnds.inf"

.Set DestinationDir=".\broadcom\wlan\otr\3100_46"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\bcm43xx.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\bcm43xxa.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\bcmwl5.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\bcmwl5.sys"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\bcmwl5a.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\bcmwl5a.sys"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\WMP54GS.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\WMP54GS.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_46\WMP54GSa.inf"

.Set DestinationDir=".\broadcom\wlan\otr\3100_64"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_64\bcm43xx.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_64\bcmwl5.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\3100_64\bcmwl5.sys"

.Set DestinationDir=".\broadcom\wlan\otr\4102"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\4102\bcmwl6.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\4102\bcmwl6.sys"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\4102\readme.txt"

.Set DestinationDir=".\broadcom\wlan\otr\4104"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\4104\bcm43xx.cat"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\4104\bcmwl5.inf"
"E:\PartImage\Ethernet_drv\broadcom\wlan\otr\4104\bcmwl5.sys"

.Set DestinationDir=".\d-link"

.Set DestinationDir=".\d-link\lan"
"E:\PartImage\Ethernet_drv\d-link\lan\De660p.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\dl2x.cat"
"E:\PartImage\Ethernet_drv\d-link\lan\dl2xcfg.dll"
"E:\PartImage\Ethernet_drv\d-link\lan\dl2xd50.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\dl2xnd4.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\dlh5x.cat"
"E:\PartImage\Ethernet_drv\d-link\lan\dlh5xnd5.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\DLHLPNDI.DLL"
"E:\PartImage\Ethernet_drv\d-link\lan\dlkfet5b.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\dlkrcb.inf"
"E:\PartImage\Ethernet_drv\d-link\lan\dlkrcb.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\dlkrtgb.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\DLKRTL.SYS"
"E:\PartImage\Ethernet_drv\d-link\lan\DLKRTS.SYS"
"E:\PartImage\Ethernet_drv\d-link\lan\dube100b.cat"
"E:\PartImage\Ethernet_drv\d-link\lan\DUBE100B.inf"
"E:\PartImage\Ethernet_drv\d-link\lan\DUBE100B.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\m4cxw2k3.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\netdl2x.inf"
"E:\PartImage\Ethernet_drv\d-link\lan\NETDL66P.INF"
"E:\PartImage\Ethernet_drv\d-link\lan\NETDLFET.CAT"
"E:\PartImage\Ethernet_drv\d-link\lan\netdlfet.inf"
"E:\PartImage\Ethernet_drv\d-link\lan\netdlh5x.inf"
"E:\PartImage\Ethernet_drv\d-link\lan\NETDLKR5.INF"
"E:\PartImage\Ethernet_drv\d-link\lan\NETDLKRN.CAT"
"E:\PartImage\Ethernet_drv\d-link\lan\NETDLKRT.INF"
"E:\PartImage\Ethernet_drv\d-link\lan\netm4cx.inf"
"E:\PartImage\Ethernet_drv\d-link\lan\readme.txt"
"E:\PartImage\Ethernet_drv\d-link\lan\vuins32.dll"

.Set DestinationDir=".\d-link\lan\530T"
"E:\PartImage\Ethernet_drv\d-link\lan\530T\gewmi.mof"
"E:\PartImage\Ethernet_drv\d-link\lan\530T\m4cx.cat"
"E:\PartImage\Ethernet_drv\d-link\lan\530T\m4cxwxp.sys"
"E:\PartImage\Ethernet_drv\d-link\lan\530T\netm4cx.inf"

.Set DestinationDir=".\d-link\lan\690TXD"
"E:\PartImage\Ethernet_drv\d-link\lan\690TXD\DLKRCB.SYS"
"E:\PartImage\Ethernet_drv\d-link\lan\690TXD\NETDLKR5.INF"

.Set DestinationDir=".\d-link\wlan"
"E:\PartImage\Ethernet_drv\d-link\wlan\A3AB.cat"
"E:\PartImage\Ethernet_drv\d-link\wlan\A3AB.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\A5AGU.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\AIRPLUS.CAT"
"E:\PartImage\Ethernet_drv\d-link\wlan\AIRPLUS.INF"
"E:\PartImage\Ethernet_drv\d-link\wlan\AIRPLUS.SYS"
"E:\PartImage\Ethernet_drv\d-link\wlan\ar5211.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\ar5523.bin"
"E:\PartImage\Ethernet_drv\d-link\wlan\autoupdate.exe"
"E:\PartImage\Ethernet_drv\d-link\wlan\CW10.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\DSB650TX.CAT"
"E:\PartImage\Ethernet_drv\d-link\wlan\DSB650TX.INF"
"E:\PartImage\Ethernet_drv\d-link\wlan\DSB650TX.SYS"
"E:\PartImage\Ethernet_drv\d-link\wlan\DWLInst.dll"
"E:\PartImage\Ethernet_drv\d-link\wlan\DWLNdi.dll"
"E:\PartImage\Ethernet_drv\d-link\wlan\net5211.cat"
"E:\PartImage\Ethernet_drv\d-link\wlan\net5211.inf"
"E:\PartImage\Ethernet_drv\d-link\wlan\NetA3AB.inf"
"E:\PartImage\Ethernet_drv\d-link\wlan\neta5agu.cat"
"E:\PartImage\Ethernet_drv\d-link\wlan\netA5AGU.inf"
"E:\PartImage\Ethernet_drv\d-link\wlan\netcw10.cat"
"E:\PartImage\Ethernet_drv\d-link\wlan\netcw10.inf"
"E:\PartImage\Ethernet_drv\d-link\wlan\NETPRISM.inf"
"E:\PartImage\Ethernet_drv\d-link\wlan\netr33x.cat"
"E:\PartImage\Ethernet_drv\d-link\wlan\NETR33X.INF"
"E:\PartImage\Ethernet_drv\d-link\wlan\NETR33X.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\NetRT61G.CAT"
"E:\PartImage\Ethernet_drv\d-link\wlan\NetRt61G.INF"
"E:\PartImage\Ethernet_drv\d-link\wlan\NETVUSBA.INF"
"E:\PartImage\Ethernet_drv\d-link\wlan\PCANDIS3.VXD"
"E:\PartImage\Ethernet_drv\d-link\wlan\PCANDIS5.SYS"
"E:\PartImage\Ethernet_drv\d-link\wlan\prismcfg.cpl"
"E:\PartImage\Ethernet_drv\d-link\wlan\PRISMIOC.dll"
"E:\PartImage\Ethernet_drv\d-link\wlan\PRISMNDS.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\PRISMNIC.cat"
"E:\PartImage\Ethernet_drv\d-link\wlan\PRISMRES.dll"
"E:\PartImage\Ethernet_drv\d-link\wlan\PRISMUSB.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\RADIO0d.BIN"
"E:\PartImage\Ethernet_drv\d-link\wlan\RADIO11.BIN"
"E:\PartImage\Ethernet_drv\d-link\wlan\RADIO15.BIN"
"E:\PartImage\Ethernet_drv\d-link\wlan\readme.txt"
"E:\PartImage\Ethernet_drv\d-link\wlan\rt61.sys"
"E:\PartImage\Ethernet_drv\d-link\wlan\VNETUSBA.SYS"
"E:\PartImage\Ethernet_drv\d-link\wlan\W32N50.dll"
"E:\PartImage\Ethernet_drv\d-link\wlan\WLANGEN.bin"

.Set DestinationDir=".\Intel"

.Set DestinationDir=".\Intel\lan"
"E:\PartImage\Ethernet_drv\Intel\lan\ANSM2KXP.INF"
"E:\PartImage\Ethernet_drv\Intel\lan\ANSP2KXP.INF"
"E:\PartImage\Ethernet_drv\Intel\lan\e1000325.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\e1000325.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1000325.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\E1000325.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1000msg.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\e1000nt5.din"
"E:\PartImage\Ethernet_drv\Intel\lan\E1000NT5.SYS"
"E:\PartImage\Ethernet_drv\Intel\lan\e100a325.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\e100ant5.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\e100b325.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\e100b325.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e100b325.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\e100b325.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e100bmsg.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\e100bnt5.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e100bnt5.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1e5032.din"
"E:\PartImage\Ethernet_drv\Intel\lan\E1e5032.SYS"
"E:\PartImage\Ethernet_drv\Intel\lan\e1e5132.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\e1e5132.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1e5132.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\e1e5132.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1k5032.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1k5032.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1k5132.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\e1k5132.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1k5132.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\e1k5132.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1q5032.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1q5032.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1q5132.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\e1q5132.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1q5132.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\e1q5132.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1qmsg.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\e1y5032.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1y5032.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\e1y5132.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\e1y5132.din"
"E:\PartImage\Ethernet_drv\Intel\lan\e1y5132.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\e1y5132.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\iamt.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\IAMT.din"
"E:\PartImage\Ethernet_drv\Intel\lan\IAMT.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\IAMT03.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\IAMT2K.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\IAMTV.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\IAMTXP.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ians2kxp.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\iansmsg.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\iansw2k.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ianswxp.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ioatco.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\IOATDMA.CAT"
"E:\PartImage\Ethernet_drv\Intel\lan\ioatdma.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\ioatdma.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\iresol.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\iresol.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\iSCSDump.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\issetup.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\iSSetup.INF"
"E:\PartImage\Ethernet_drv\Intel\lan\iSSetup.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe5132.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe5132.din"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe5132.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe5132.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe6032.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe6032.din"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe6032.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\ixe6032.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ixemsg.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\ixg6032.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\ixg6032.din"
"E:\PartImage\Ethernet_drv\Intel\lan\ixg6032.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\ixg6032.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ixgb325.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\ixgb325.din"
"E:\PartImage\Ethernet_drv\Intel\lan\ixgb325.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\ixgb325.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ixgb3251.din"
"E:\PartImage\Ethernet_drv\Intel\lan\ixgb3251.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\ixgbmsg.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\nicco2.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicCo26.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicInE6.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicInIXE.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicInst.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicInst6.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicInstE.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicInstG.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\NicInstQ.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\PRONtObj.dll"
"E:\PartImage\Ethernet_drv\Intel\lan\PROUnstl.exe"
"E:\PartImage\Ethernet_drv\Intel\lan\qd16032.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\qd16032.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\qd16032.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\qd25232.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\qd25232.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\qd25232.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\qd26032.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\qd26032.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\qd26032.sys"
"E:\PartImage\Ethernet_drv\Intel\lan\qd3nodrv.cat"
"E:\PartImage\Ethernet_drv\Intel\lan\qd3nodrv.inf"
"E:\PartImage\Ethernet_drv\Intel\lan\ReadMe.txt"

.Set DestinationDir=".\Intel\lan\old"
"E:\PartImage\Ethernet_drv\Intel\lan\old\E100B325.CAT"
"E:\PartImage\Ethernet_drv\Intel\lan\old\E100B325.DIN"
"E:\PartImage\Ethernet_drv\Intel\lan\old\E100B325.INF"
"E:\PartImage\Ethernet_drv\Intel\lan\old\E100B325.SYS"
"E:\PartImage\Ethernet_drv\Intel\lan\old\E100BMSG.DLL"
"E:\PartImage\Ethernet_drv\Intel\lan\old\INTELNIC.DLL"
"E:\PartImage\Ethernet_drv\Intel\lan\old\PROUnstl.exe"

.Set DestinationDir=".\Intel\wlan"
"E:\PartImage\Ethernet_drv\Intel\wlan\readme.txt"

.Set DestinationDir=".\Intel\wlan\2011"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011\netwlan5.cat"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011\NetWlan5.img"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011\NetWlan5.inf"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011\NetWlan5.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011\readme.txt"

.Set DestinationDir=".\Intel\wlan\2011b"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011b\cw51usb.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011b\MPFWRES.dll"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011b\readme.txt"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011b\USBCoIns.dll"
"E:\PartImage\Ethernet_drv\Intel\wlan\2011b\wlanusb.inf"

.Set DestinationDir=".\Intel\wlan\2100_2200G"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\CX2NC51.INF"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\CX2NC51.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\readme.txt"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\W20MLRES.DLL"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\W20NCPA.DLL"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\W22PMLRS.DLL"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\W22PNCPA.DLL"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\w70n5.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\w70n501.inf"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\w70n51.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\2100_2200G\w70n5msg.dll"

.Set DestinationDir=".\Intel\wlan\2200BG_5350"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw2c32.dll"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw2r32.dll"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw4c32.DLL"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw4r32.DLL"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw4x32.CAT"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw4x32.INF"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw4x32.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw5c32.dll"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw5r32.dll"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw5x32.cat"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw5x32.inf"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\NETw5x32.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\readme.txt"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\w29n51.cat"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\w29n51.inf"
"E:\PartImage\Ethernet_drv\Intel\wlan\2200BG_5350\w29n51.sys"

.Set DestinationDir=".\Intel\wlan\5000"
"E:\PartImage\Ethernet_drv\Intel\wlan\5000\OEMSETUP.INF"
"E:\PartImage\Ethernet_drv\Intel\wlan\5000\readme.txt"
"E:\PartImage\Ethernet_drv\Intel\wlan\5000\wl50nd4.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\5000\wl50nd5.inf"
"E:\PartImage\Ethernet_drv\Intel\wlan\5000\wl50nd5.sys"
"E:\PartImage\Ethernet_drv\Intel\wlan\5000\wl5cfg.dll"
"E:\PartImage\Ethernet_drv\Intel\wlan\5000\WL5NDI.DLL"

.Set DestinationDir=".\marvell"

.Set DestinationDir=".\marvell\lan"

.Set DestinationDir=".\marvell\lan\1057"
"E:\PartImage\Ethernet_drv\marvell\lan\1057\ReadMe.txt"
"E:\PartImage\Ethernet_drv\marvell\lan\1057\yk51x86.cat"
"E:\PartImage\Ethernet_drv\marvell\lan\1057\yk51x86.inf"
"E:\PartImage\Ethernet_drv\marvell\lan\1057\yk51x86.sys"

.Set DestinationDir=".\marvell\lan\1060"
"E:\PartImage\Ethernet_drv\marvell\lan\1060\readme.txt"
"E:\PartImage\Ethernet_drv\marvell\lan\1060\yk51x86.cat"
"E:\PartImage\Ethernet_drv\marvell\lan\1060\yk51x86.inf"
"E:\PartImage\Ethernet_drv\marvell\lan\1060\yk51x86.sys"
"E:\PartImage\Ethernet_drv\marvell\lan\1060\ykx32psm.dll"

.Set DestinationDir=".\marvell\lan\846"
"E:\PartImage\Ethernet_drv\marvell\lan\846\yk51x86.cat"
"E:\PartImage\Ethernet_drv\marvell\lan\846\yk51x86.inf"
"E:\PartImage\Ethernet_drv\marvell\lan\846\yk51x86.sys"

.Set DestinationDir=".\marvell\lan\851"
"E:\PartImage\Ethernet_drv\marvell\lan\851\readme.txt"
"E:\PartImage\Ethernet_drv\marvell\lan\851\yk51x86.inf"
"E:\PartImage\Ethernet_drv\marvell\lan\851\yk51x86.sys"

.Set DestinationDir=".\marvell\wlan"
"E:\PartImage\Ethernet_drv\marvell\wlan\CB55N50.sys"
"E:\PartImage\Ethernet_drv\marvell\wlan\CB55N51.sys"
"E:\PartImage\Ethernet_drv\marvell\wlan\cb55n5x.cat"
"E:\PartImage\Ethernet_drv\marvell\wlan\CB55N5x.inf"
"E:\PartImage\Ethernet_drv\marvell\wlan\mrv8335.cat"
"E:\PartImage\Ethernet_drv\marvell\wlan\mrv8335.inf"
"E:\PartImage\Ethernet_drv\marvell\wlan\MRV8335XP.sys"
"E:\PartImage\Ethernet_drv\marvell\wlan\MRV8K51.INF"
"E:\PartImage\Ethernet_drv\marvell\wlan\MRV8K51.SYS"
"E:\PartImage\Ethernet_drv\marvell\wlan\Mrvw125.sys"
"E:\PartImage\Ethernet_drv\marvell\wlan\Mrvw245.sys"
"E:\PartImage\Ethernet_drv\marvell\wlan\netmw125.cat"
"E:\PartImage\Ethernet_drv\marvell\wlan\netmw125.inf"
"E:\PartImage\Ethernet_drv\marvell\wlan\netmw245.inf"
"E:\PartImage\Ethernet_drv\marvell\wlan\readme.txt"

.Set DestinationDir=".\nvidia"
"E:\PartImage\Ethernet_drv\nvidia\readme.txt"

.Set DestinationDir=".\nvidia\0416"
"E:\PartImage\Ethernet_drv\nvidia\0416\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\0416\nvcoe.dll"
"E:\PartImage\Ethernet_drv\nvidia\0416\nvenet.cat"
"E:\PartImage\Ethernet_drv\nvidia\0416\nvenet.nvu"
"E:\PartImage\Ethernet_drv\nvidia\0416\nvenet.sys"
"E:\PartImage\Ethernet_drv\nvidia\0416\nvenetxp.inf"
"E:\PartImage\Ethernet_drv\nvidia\0416\nvuenet.exe"

.Set DestinationDir=".\nvidia\0482"
"E:\PartImage\Ethernet_drv\nvidia\0482\bdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\0482\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvconrm.dll"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvefd2k.sys"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvefdxp.sys"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvenetfd.cat"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvenetfd.inf"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvenetfd.tag"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvnetbus.cat"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvnetbus.inf"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvnetbus.sys"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvnetbus.tag"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvnrm.nvu"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvnrm.sys"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvsnpu.sys"
"E:\PartImage\Ethernet_drv\nvidia\0482\nvunrm.exe"

.Set DestinationDir=".\nvidia\5025"
"E:\PartImage\Ethernet_drv\nvidia\5025\bdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1028.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1031.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1034.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1036.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1040.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1041.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1042.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l1046.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\fdco_l2052.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvconrm.dll"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvefd2k.sys"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvefdxp.sys"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvenetfd.cat"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvenetfd.inf"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvenetfd.tag"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvnetbus.cat"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvnetbus.inf"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvnetbus.sys"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvnetbus.tag"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvnrm.nvu"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvnrm.sys"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvsnpu.sys"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvtcp.sys"
"E:\PartImage\Ethernet_drv\nvidia\5025\nvunrm.exe"

.Set DestinationDir=".\nvidia\6521"
"E:\PartImage\Ethernet_drv\nvidia\6521\bdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6521\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvconrm.dll"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvefd2k.sys"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvefdxp.sys"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvenetfd.cat"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvenetfd.inf"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvenetfd.tag"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvnetbus.cat"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvnetbus.inf"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvnetbus.sys"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvnetbus.tag"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvnrm.nvu"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvnrm.sys"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvsnpu.sys"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvtcp.sys"
"E:\PartImage\Ethernet_drv\nvidia\6521\nvunrm.exe"

.Set DestinationDir=".\nvidia\6565"
"E:\PartImage\Ethernet_drv\nvidia\6565\bdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6565\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvconrm.dll"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvefd2k.sys"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvefdxp.sys"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvenetfd.inf"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvenetfd.tag"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvnetbus.inf"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvnetbus.sys"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvnetbus.tag"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvnrm.nvu"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvnrm.sys"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvphy.bin"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvsnpu.sys"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvtcp.sys"
"E:\PartImage\Ethernet_drv\nvidia\6565\nvunrm.exe"

.Set DestinationDir=".\nvidia\6764"
"E:\PartImage\Ethernet_drv\nvidia\6764\bdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6764\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvconrm.dll"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvefd2k.sys"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvefdxp.sys"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvenetfd.inf"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvenetfd.tag"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvnetbus.inf"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvnetbus.sys"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvnetbus.tag"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvnrm.nvu"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvnrm.sys"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvphy.bin"
"E:\PartImage\Ethernet_drv\nvidia\6764\nvunrm.exe"

.Set DestinationDir=".\nvidia\6781"
"E:\PartImage\Ethernet_drv\nvidia\6781\bdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6781\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvconrm.dll"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvefd2k.sys"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvefdxp.sys"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvenetfd.inf"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvenetfd.tag"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvnetbus.inf"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvnetbus.sys"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvnetbus.tag"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvnrm.nvu"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvnrm.sys"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvphy.bin"
"E:\PartImage\Ethernet_drv\nvidia\6781\nvunrm.exe"

.Set DestinationDir=".\nvidia\6789"
"E:\PartImage\Ethernet_drv\nvidia\6789\bdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6789\fdco1.dll"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvconrm.dll"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvefd2k.sys"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvefdxp.sys"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvenetfd.cat"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvenetfd.inf"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvenetfd.tag"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvnetbus.cat"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvnetbus.inf"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvnetbus.sys"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvnetbus.tag"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvnrm.nvu"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvnrm.sys"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvphy.bin"
"E:\PartImage\Ethernet_drv\nvidia\6789\nvunrm.exe"

.Set DestinationDir=".\other"

.Set DestinationDir=".\other\a"
"E:\PartImage\Ethernet_drv\other\a\abovends.sys"
"E:\PartImage\Ethernet_drv\other\a\acgprsxp.sys"
"E:\PartImage\Ethernet_drv\other\a\ADM8211.sys"
"E:\PartImage\Ethernet_drv\other\a\ADM8511.SYS"
"E:\PartImage\Ethernet_drv\other\a\ADM9X.SYS"
"E:\PartImage\Ethernet_drv\other\a\agr1310.cat"
"E:\PartImage\Ethernet_drv\other\a\agr1310.inf"
"E:\PartImage\Ethernet_drv\other\a\agr1310_51.sys"
"E:\PartImage\Ethernet_drv\other\a\Air555.sys"
"E:\PartImage\Ethernet_drv\other\a\Am1772.cat"
"E:\PartImage\Ethernet_drv\other\a\Am772.sys"
"E:\PartImage\Ethernet_drv\other\a\AN983.SYS"
"E:\PartImage\Ethernet_drv\other\a\An986n.inf"
"E:\PartImage\Ethernet_drv\other\a\ar5211.sys"
"E:\PartImage\Ethernet_drv\other\a\ar5416.sys"
"E:\PartImage\Ethernet_drv\other\a\AR5523.BIN"
"E:\PartImage\Ethernet_drv\other\a\AR5523.SYS"
"E:\PartImage\Ethernet_drv\other\a\ATNICm51.sys"
"E:\PartImage\Ethernet_drv\other\a\atnicm5x.cat"
"E:\PartImage\Ethernet_drv\other\a\Ax88140.inf"
"E:\PartImage\Ethernet_drv\other\a\ax88140.sys"
"E:\PartImage\Ethernet_drv\other\a\ax88178.inf"
"E:\PartImage\Ethernet_drv\other\a\ax88178.sys"
"E:\PartImage\Ethernet_drv\other\a\ax88180.inf"
"E:\PartImage\Ethernet_drv\other\a\ax88180.sys"
"E:\PartImage\Ethernet_drv\other\a\ax88190.inf"
"E:\PartImage\Ethernet_drv\other\a\ax88190.sys"
"E:\PartImage\Ethernet_drv\other\a\ax88772.inf"
"E:\PartImage\Ethernet_drv\other\a\ax88772.sys"
"E:\PartImage\Ethernet_drv\other\a\ax88796b.inf"
"E:\PartImage\Ethernet_drv\other\a\ax88796b.sys"
"E:\PartImage\Ethernet_drv\other\a\CBG2402.bin"
"E:\PartImage\Ethernet_drv\other\a\CBG24021.sys"
"E:\PartImage\Ethernet_drv\other\a\CInsx500.dll"
"E:\PartImage\Ethernet_drv\other\a\csco21.sys"
"E:\PartImage\Ethernet_drv\other\a\dcn530n5.sys"
"E:\PartImage\Ethernet_drv\other\a\DM9102C.CAT"
"E:\PartImage\Ethernet_drv\other\a\DM9PCI5.SYS"
"E:\PartImage\Ethernet_drv\other\a\DP83820.sys"
"E:\PartImage\Ethernet_drv\other\a\fastnic.inf"
"E:\PartImage\Ethernet_drv\other\a\FastNIC.SYS"
"E:\PartImage\Ethernet_drv\other\a\FwRad16.bin"
"E:\PartImage\Ethernet_drv\other\a\FwRad17.bin"
"E:\PartImage\Ethernet_drv\other\a\IP100.INF"
"E:\PartImage\Ethernet_drv\other\a\IP100N51.SYS"
"E:\PartImage\Ethernet_drv\other\a\ipfnd51.sys"
"E:\PartImage\Ethernet_drv\other\a\ipgdnd51.sys"
"E:\PartImage\Ethernet_drv\other\a\l151x86.cat"
"E:\PartImage\Ethernet_drv\other\a\l151x86.inf"
"E:\PartImage\Ethernet_drv\other\a\l151x86.sys"
"E:\PartImage\Ethernet_drv\other\a\l250x86.inf"
"E:\PartImage\Ethernet_drv\other\a\l250x86.sys"
"E:\PartImage\Ethernet_drv\other\a\l251x86.cat"
"E:\PartImage\Ethernet_drv\other\a\l251x86.inf"
"E:\PartImage\Ethernet_drv\other\a\l251x86.sys"
"E:\PartImage\Ethernet_drv\other\a\LAHPCM25.SYS"
"E:\PartImage\Ethernet_drv\other\a\mdmac555.cat"
"E:\PartImage\Ethernet_drv\other\a\mdmac555.inf"
"E:\PartImage\Ethernet_drv\other\a\mdmacgprs.cat"
"E:\PartImage\Ethernet_drv\other\a\mdmacgprs.inf"
"E:\PartImage\Ethernet_drv\other\a\mfac555.cat"
"E:\PartImage\Ethernet_drv\other\a\MFAC555.INF"
"E:\PartImage\Ethernet_drv\other\a\mfacgprs.cat"
"E:\PartImage\Ethernet_drv\other\a\mfacgprs.inf"
"E:\PartImage\Ethernet_drv\other\a\net21.inf"
"E:\PartImage\Ethernet_drv\other\a\net5211.cat"
"E:\PartImage\Ethernet_drv\other\a\net5211.inf"
"E:\PartImage\Ethernet_drv\other\a\net5416.cat"
"E:\PartImage\Ethernet_drv\other\a\net5416.inf"
"E:\PartImage\Ethernet_drv\other\a\NET5523.CAT"
"E:\PartImage\Ethernet_drv\other\a\NET5523.INF"
"E:\PartImage\Ethernet_drv\other\a\NET83820.INF"
"E:\PartImage\Ethernet_drv\other\a\NET8511.INF"
"E:\PartImage\Ethernet_drv\other\a\netA504.inf"
"E:\PartImage\Ethernet_drv\other\a\netac555.cat"
"E:\PartImage\Ethernet_drv\other\a\netac555.inf"
"E:\PartImage\Ethernet_drv\other\a\netacgprs.cat"
"E:\PartImage\Ethernet_drv\other\a\netacgprs.inf"
"E:\PartImage\Ethernet_drv\other\a\Netadm11.inf"
"E:\PartImage\Ethernet_drv\other\a\Netadm9x.inf"
"E:\PartImage\Ethernet_drv\other\a\NETAHMV2.INF"
"E:\PartImage\Ethernet_drv\other\a\NetAm772.inf"
"E:\PartImage\Ethernet_drv\other\a\NETAN983.INF"
"E:\PartImage\Ethernet_drv\other\a\NetAni.inf"
"E:\PartImage\Ethernet_drv\other\a\NETATNIC.INF"
"E:\PartImage\Ethernet_drv\other\a\netcb240.inf"
"E:\PartImage\Ethernet_drv\other\a\NETDC530.CAT"
"E:\PartImage\Ethernet_drv\other\a\netdc530.inf"
"E:\PartImage\Ethernet_drv\other\a\netdmA.inf"
"E:\PartImage\Ethernet_drv\other\a\netipf.inf"
"E:\PartImage\Ethernet_drv\other\a\netipgd.inf"
"E:\PartImage\Ethernet_drv\other\a\NETVUSBR.INF"
"E:\PartImage\Ethernet_drv\other\a\netX500.inf"
"E:\PartImage\Ethernet_drv\other\a\OEMSETUP.INF"
"E:\PartImage\Ethernet_drv\other\a\OEMSETUP2.INF"
"E:\PartImage\Ethernet_drv\other\a\PCX500.SYS"
"E:\PartImage\Ethernet_drv\other\a\pcx500.xp"
"E:\PartImage\Ethernet_drv\other\a\pcx500b.img"
"E:\PartImage\Ethernet_drv\other\a\PCX500MP.SYS"
"E:\PartImage\Ethernet_drv\other\a\pcx504.51"
"E:\PartImage\Ethernet_drv\other\a\PCX504.sys"
"E:\PartImage\Ethernet_drv\other\a\pcx504a.img"
"E:\PartImage\Ethernet_drv\other\a\pcx504b.img"
"E:\PartImage\Ethernet_drv\other\a\PRISMA00.inf"
"E:\PartImage\Ethernet_drv\other\a\PRISMA00.sys"
"E:\PartImage\Ethernet_drv\other\a\PRISMAPI.dll"
"E:\PartImage\Ethernet_drv\other\a\prismcfg.cpl"
"E:\PartImage\Ethernet_drv\other\a\PRISMDCB.arm"
"E:\PartImage\Ethernet_drv\other\a\PRISMDOM.ini"
"E:\PartImage\Ethernet_drv\other\a\PRISMICB.arm"
"E:\PartImage\Ethernet_drv\other\a\PRISMICB.inf"
"E:\PartImage\Ethernet_drv\other\a\PRISMICB.sys"
"E:\PartImage\Ethernet_drv\other\a\prismioc.dll"
"E:\PartImage\Ethernet_drv\other\a\PRISMNDI.dll"
"E:\PartImage\Ethernet_drv\other\a\prismnds.sys"
"E:\PartImage\Ethernet_drv\other\a\PRISMNIC.inf"
"E:\PartImage\Ethernet_drv\other\a\prismres.dll"
"E:\PartImage\Ethernet_drv\other\a\prismsta.exe"
"E:\PartImage\Ethernet_drv\other\a\PRISMSVR.exe"
"E:\PartImage\Ethernet_drv\other\a\prismusb.sys"
"E:\PartImage\Ethernet_drv\other\a\readme.txt"
"E:\PartImage\Ethernet_drv\other\a\remove.exe"
"E:\PartImage\Ethernet_drv\other\a\rt2400.INF"
"E:\PartImage\Ethernet_drv\other\a\rt2400.sys"
"E:\PartImage\Ethernet_drv\other\a\RT2500.CAT"
"E:\PartImage\Ethernet_drv\other\a\Rt2500.INF"
"E:\PartImage\Ethernet_drv\other\a\rt2500.sys"
"E:\PartImage\Ethernet_drv\other\a\Rt2500b.INF"
"E:\PartImage\Ethernet_drv\other\a\rt2500usb.cat"
"E:\PartImage\Ethernet_drv\other\a\rt2500usb.inf"
"E:\PartImage\Ethernet_drv\other\a\rt2500usb.sys"
"E:\PartImage\Ethernet_drv\other\a\rt2860.cat"
"E:\PartImage\Ethernet_drv\other\a\rt2860.inf"
"E:\PartImage\Ethernet_drv\other\a\rt2860.sys"
"E:\PartImage\Ethernet_drv\other\a\rt61.inf"
"E:\PartImage\Ethernet_drv\other\a\rt61.sys"
"E:\PartImage\Ethernet_drv\other\a\rt73.cat"
"E:\PartImage\Ethernet_drv\other\a\rt73.inf"
"E:\PartImage\Ethernet_drv\other\a\rt73.sys"
"E:\PartImage\Ethernet_drv\other\a\TNET1130.INF"
"E:\PartImage\Ethernet_drv\other\a\tnet1130.sys"
"E:\PartImage\Ethernet_drv\other\a\uninstall.exe"
"E:\PartImage\Ethernet_drv\other\a\VNETUSBR.SYS"
"E:\PartImage\Ethernet_drv\other\a\vssver.scc"
"E:\PartImage\Ethernet_drv\other\a\WAAGS48B.DLL"
"E:\PartImage\Ethernet_drv\other\a\WAAGS48D.DLL"
"E:\PartImage\Ethernet_drv\other\a\WAAGS51B.DLL"
"E:\PartImage\Ethernet_drv\other\a\WCAGS48B.EXE"
"E:\PartImage\Ethernet_drv\other\a\WCAGS48D.EXE"
"E:\PartImage\Ethernet_drv\other\a\WCAGS51B.EXE"
"E:\PartImage\Ethernet_drv\other\a\WDAGS48.DLL"
"E:\PartImage\Ethernet_drv\other\a\WDAGS48B.DLL"
"E:\PartImage\Ethernet_drv\other\a\WDAGS48C.DLL"
"E:\PartImage\Ethernet_drv\other\a\WDAGS48D.DLL"
"E:\PartImage\Ethernet_drv\other\a\WDAGS51.DLL"
"E:\PartImage\Ethernet_drv\other\a\WDAGS51B.DLL"
"E:\PartImage\Ethernet_drv\other\a\WFAGS48B.SYS"
"E:\PartImage\Ethernet_drv\other\a\WIAGS51.DLL"
"E:\PartImage\Ethernet_drv\other\a\wlags2x.cat"
"E:\PartImage\Ethernet_drv\other\a\WLAGS48B.SYS"
"E:\PartImage\Ethernet_drv\other\a\WLAGS48D.SYS"
"E:\PartImage\Ethernet_drv\other\a\WLAGS51B.SYS"
"E:\PartImage\Ethernet_drv\other\a\WLAGSALL.INF"
"E:\PartImage\Ethernet_drv\other\a\wlanCIG.arm"
"E:\PartImage\Ethernet_drv\other\a\wlanCIG.cat"
"E:\PartImage\Ethernet_drv\other\a\wlanCIG.inf"
"E:\PartImage\Ethernet_drv\other\a\wlanCIG.sys"
"E:\PartImage\Ethernet_drv\other\a\WLANCRN.cat"
"E:\PartImage\Ethernet_drv\other\a\WLANCRN.inf"
"E:\PartImage\Ethernet_drv\other\a\WLANCRN.sys"
"E:\PartImage\Ethernet_drv\other\a\wlanioc.vxd"
"E:\PartImage\Ethernet_drv\other\a\WLANNIC.INF"
"E:\PartImage\Ethernet_drv\other\a\WLANPCI.cat"
"E:\PartImage\Ethernet_drv\other\a\WLANPCI.inf"
"E:\PartImage\Ethernet_drv\other\a\WLANPCI.sys"
"E:\PartImage\Ethernet_drv\other\a\wlanuzg.cat"
"E:\PartImage\Ethernet_drv\other\a\WlanUZG.inf"
"E:\PartImage\Ethernet_drv\other\a\WlanUZXP.SYS"
"E:\PartImage\Ethernet_drv\other\a\WNAGS.CNT"
"E:\PartImage\Ethernet_drv\other\a\WNAGS.HLP"
"E:\PartImage\Ethernet_drv\other\a\WNAGS48B.CPL"
"E:\PartImage\Ethernet_drv\other\a\WNAGS48D.CPL"
"E:\PartImage\Ethernet_drv\other\a\WNAGS51B.CPL"
"E:\PartImage\Ethernet_drv\other\a\wni6000.bin"
"E:\PartImage\Ethernet_drv\other\a\WNIhdd51.sys"
"E:\PartImage\Ethernet_drv\other\a\WS01UPh.bin"
"E:\PartImage\Ethernet_drv\other\a\ZD02_XP.sys"
"E:\PartImage\Ethernet_drv\other\a\ZD11BUXP.SYS"
"E:\PartImage\Ethernet_drv\other\a\ZD11UXP.sys"
"E:\PartImage\Ethernet_drv\other\a\ZD1201U.CAT"
"E:\PartImage\Ethernet_drv\other\a\ZD1201U.INF"
"E:\PartImage\Ethernet_drv\other\a\ZD1201U.sys"
"E:\PartImage\Ethernet_drv\other\a\ZD1201UX.INF"
"E:\PartImage\Ethernet_drv\other\a\ZD1202.inf"
"E:\PartImage\Ethernet_drv\other\a\ZD1211BU.INF"
"E:\PartImage\Ethernet_drv\other\a\ZD1211U.inf"
"E:\PartImage\Ethernet_drv\other\a\ZD1212P.INF"
"E:\PartImage\Ethernet_drv\other\a\ZD12PXP.SYS"
"E:\PartImage\Ethernet_drv\other\a\ZD1UXP.sys"

.Set DestinationDir=".\other\b"
"E:\PartImage\Ethernet_drv\other\b\ACC07D.SYS"
"E:\PartImage\Ethernet_drv\other\b\ACCPCI.SYS"
"E:\PartImage\Ethernet_drv\other\b\ACTNCFG.cpl"
"E:\PartImage\Ethernet_drv\other\b\ACTNIOC.dll"
"E:\PartImage\Ethernet_drv\other\b\ACTNNDS.sys"
"E:\PartImage\Ethernet_drv\other\b\ACTNNIC.cat"
"E:\PartImage\Ethernet_drv\other\b\ACTNNIC.inf"
"E:\PartImage\Ethernet_drv\other\b\ACTNRES.dll"
"E:\PartImage\Ethernet_drv\other\b\ACTNSTA.exe"
"E:\PartImage\Ethernet_drv\other\b\ACTNUSB.sys"
"E:\PartImage\Ethernet_drv\other\b\ag300n5.sys"
"E:\PartImage\Ethernet_drv\other\b\aninet.cat"
"E:\PartImage\Ethernet_drv\other\b\ar5210b.sys"
"E:\PartImage\Ethernet_drv\other\b\ar5211.sys"
"E:\PartImage\Ethernet_drv\other\b\ar5416.sys"
"E:\PartImage\Ethernet_drv\other\b\ar5523.sys"
"E:\PartImage\Ethernet_drv\other\b\athfmwdl.inf"
"E:\PartImage\Ethernet_drv\other\b\athfmwdl.sys"
"E:\PartImage\Ethernet_drv\other\b\athw.sys"
"E:\PartImage\Ethernet_drv\other\b\CBG54.sys"
"E:\PartImage\Ethernet_drv\other\b\CBG54L2x.sys"
"E:\PartImage\Ethernet_drv\other\b\EN1208.SYS"
"E:\PartImage\Ethernet_drv\other\b\EN5251N5.SYS"
"E:\PartImage\Ethernet_drv\other\b\FA311V2.SYS"
"E:\PartImage\Ethernet_drv\other\b\FA511ND5.sys"
"E:\PartImage\Ethernet_drv\other\b\FwRad16.bin"
"E:\PartImage\Ethernet_drv\other\b\FwRad17.bin"
"E:\PartImage\Ethernet_drv\other\b\GA311ND5.SYS"
"E:\PartImage\Ethernet_drv\other\b\GA311NXP.CAT"
"E:\PartImage\Ethernet_drv\other\b\install_cur_inf_all.sh"
"E:\PartImage\Ethernet_drv\other\b\l1e51x86.cat"
"E:\PartImage\Ethernet_drv\other\b\l1e51x86.inf"
"E:\PartImage\Ethernet_drv\other\b\l1e51x86.sys"
"E:\PartImage\Ethernet_drv\other\b\ls6000.bin"
"E:\PartImage\Ethernet_drv\other\b\lssrx51.sys"
"E:\PartImage\Ethernet_drv\other\b\MA521nd5.cat"
"E:\PartImage\Ethernet_drv\other\b\MA521nd5.sys"
"E:\PartImage\Ethernet_drv\other\b\NET1208.INF"
"E:\PartImage\Ethernet_drv\other\b\NET2G54L.inf"
"E:\PartImage\Ethernet_drv\other\b\net2pg54.inf"
"E:\PartImage\Ethernet_drv\other\b\net5210b.inf"
"E:\PartImage\Ethernet_drv\other\b\net5211.inf"
"E:\PartImage\Ethernet_drv\other\b\net5416.cat"
"E:\PartImage\Ethernet_drv\other\b\net5416.inf"
"E:\PartImage\Ethernet_drv\other\b\net5523.inf"
"E:\PartImage\Ethernet_drv\other\b\NETACC07.CAT"
"E:\PartImage\Ethernet_drv\other\b\NETACC07.INF"
"E:\PartImage\Ethernet_drv\other\b\NETACC51.CAT"
"E:\PartImage\Ethernet_drv\other\b\NETACC51.INF"
"E:\PartImage\Ethernet_drv\other\b\NETACCP.INF"
"E:\PartImage\Ethernet_drv\other\b\netag3n.cat"
"E:\PartImage\Ethernet_drv\other\b\netag3n.inf"
"E:\PartImage\Ethernet_drv\other\b\NETANI.INF"
"E:\PartImage\Ethernet_drv\other\b\NETANIB.INF"
"E:\PartImage\Ethernet_drv\other\b\netathw.cat"
"E:\PartImage\Ethernet_drv\other\b\netathw.inf"
"E:\PartImage\Ethernet_drv\other\b\netcbg54.inf"
"E:\PartImage\Ethernet_drv\other\b\NETCG54L.INF"
"E:\PartImage\Ethernet_drv\other\b\NETFA311V2.INF"
"E:\PartImage\Ethernet_drv\other\b\NETFA511.CAT"
"E:\PartImage\Ethernet_drv\other\b\NETFA511.inf"
"E:\PartImage\Ethernet_drv\other\b\netg54s.inf"
"E:\PartImage\Ethernet_drv\other\b\NETGA311.INF"
"E:\PartImage\Ethernet_drv\other\b\NETMA521.inf"
"E:\PartImage\Ethernet_drv\other\b\netv558.inf"
"E:\PartImage\Ethernet_drv\other\b\netvusbr.inf"
"E:\PartImage\Ethernet_drv\other\b\OEMSETUP.inf"
"E:\PartImage\Ethernet_drv\other\b\PRISMA00.sys"
"E:\PartImage\Ethernet_drv\other\b\PRISMIOC.DLL"
"E:\PartImage\Ethernet_drv\other\b\PRISMNDS.SYS"
"E:\PartImage\Ethernet_drv\other\b\PRISMRES.DLL"
"E:\PartImage\Ethernet_drv\other\b\ReadMe.txt"
"E:\PartImage\Ethernet_drv\other\b\RT2400.INF"
"E:\PartImage\Ethernet_drv\other\b\RT2400.SYS"
"E:\PartImage\Ethernet_drv\other\b\rt2500.cat"
"E:\PartImage\Ethernet_drv\other\b\Rt2500.INF"
"E:\PartImage\Ethernet_drv\other\b\rt2500.sys"
"E:\PartImage\Ethernet_drv\other\b\SMCWCBG.INF"
"E:\PartImage\Ethernet_drv\other\b\SMCWCBG.sys"
"E:\PartImage\Ethernet_drv\other\b\SMCWCBTG.INF"
"E:\PartImage\Ethernet_drv\other\b\SMCWCBTG.sys"
"E:\PartImage\Ethernet_drv\other\b\stacfg00.cpl"
"E:\PartImage\Ethernet_drv\other\b\stacfg00.dll"
"E:\PartImage\Ethernet_drv\other\b\tmimo3.bin"
"E:\PartImage\Ethernet_drv\other\b\tmimo31P.sys"
"E:\PartImage\Ethernet_drv\other\b\tmimo3P.inf"
"E:\PartImage\Ethernet_drv\other\b\tnet1130.sys"
"E:\PartImage\Ethernet_drv\other\b\vnet558x.sys"
"E:\PartImage\Ethernet_drv\other\b\vnetusbr.sys"
"E:\PartImage\Ethernet_drv\other\b\WLANDCB.arm"
"E:\PartImage\Ethernet_drv\other\b\WLANDCB.sys"
"E:\PartImage\Ethernet_drv\other\b\WlanDom.ini"
"E:\PartImage\Ethernet_drv\other\b\wlannic.inf"
"E:\PartImage\Ethernet_drv\other\b\WN4201B.cat"
"E:\PartImage\Ethernet_drv\other\b\WN4201B.inf"
"E:\PartImage\Ethernet_drv\other\b\wni6000.bin"
"E:\PartImage\Ethernet_drv\other\b\WniHdd51.sys"
"E:\PartImage\Ethernet_drv\other\b\WNPCMX.INF"

.Set DestinationDir=".\realtek"

.Set DestinationDir=".\realtek\lan"
"E:\PartImage\Ethernet_drv\realtek\lan\readme.txt"

.Set DestinationDir=".\realtek\lan\621"
"E:\PartImage\Ethernet_drv\realtek\lan\621\GA511ND5.CAT"
"E:\PartImage\Ethernet_drv\realtek\lan\621\GA511NXP.SYS"
"E:\PartImage\Ethernet_drv\realtek\lan\621\NETGA511.INF"
"E:\PartImage\Ethernet_drv\realtek\lan\621\ReadMe.txt"

.Set DestinationDir=".\realtek\lan\674"
"E:\PartImage\Ethernet_drv\realtek\lan\674\netrtle.cat"
"E:\PartImage\Ethernet_drv\realtek\lan\674\Netrtle.inf"
"E:\PartImage\Ethernet_drv\realtek\lan\674\Rtenicxp.sys"

.Set DestinationDir=".\realtek\lan\680"
"E:\PartImage\Ethernet_drv\realtek\lan\680\netrtle.cat"
"E:\PartImage\Ethernet_drv\realtek\lan\680\Netrtle.inf"
"E:\PartImage\Ethernet_drv\realtek\lan\680\ReadMe.txt"
"E:\PartImage\Ethernet_drv\realtek\lan\680\Rtenicxp.sys"

.Set DestinationDir=".\realtek\lan\687"
"E:\PartImage\Ethernet_drv\realtek\lan\687\netrtl.cat"
"E:\PartImage\Ethernet_drv\realtek\lan\687\Netrtlx.inf"
"E:\PartImage\Ethernet_drv\realtek\lan\687\Rtnicxp.sys"

.Set DestinationDir=".\realtek\lan\708"
"E:\PartImage\Ethernet_drv\realtek\lan\708\netrtle.cat"
"E:\PartImage\Ethernet_drv\realtek\lan\708\Netrtle.inf"
"E:\PartImage\Ethernet_drv\realtek\lan\708\Rtenicxp.sys"
"E:\PartImage\Ethernet_drv\realtek\lan\708\RtNicprop32.DLL"

.Set DestinationDir=".\realtek\wlan"
"E:\PartImage\Ethernet_drv\realtek\wlan\readme.txt"

.Set DestinationDir=".\realtek\wlan\8150usb"
"E:\PartImage\Ethernet_drv\realtek\wlan\8150usb\NET8150.INF"
"E:\PartImage\Ethernet_drv\realtek\wlan\8150usb\RTL8150.SYS"

.Set DestinationDir=".\realtek\wlan\8180"
"E:\PartImage\Ethernet_drv\realtek\wlan\8180\NET8180.INF"
"E:\PartImage\Ethernet_drv\realtek\wlan\8180\rtl8180.sys"

.Set DestinationDir=".\realtek\wlan\8185l"
"E:\PartImage\Ethernet_drv\realtek\wlan\8185l\net8185.cat"
"E:\PartImage\Ethernet_drv\realtek\wlan\8185l\net8185.inf"
"E:\PartImage\Ethernet_drv\realtek\wlan\8185l\rtl8185.sys"

.Set DestinationDir=".\realtek\wlan\8187b"
"E:\PartImage\Ethernet_drv\realtek\wlan\8187b\net8187b.cat"
"E:\PartImage\Ethernet_drv\realtek\wlan\8187b\net8187b.inf"
"E:\PartImage\Ethernet_drv\realtek\wlan\8187b\rtl8187B.sys"

.Set DestinationDir=".\realtek\wlan\8187l"
"E:\PartImage\Ethernet_drv\realtek\wlan\8187l\netrtuw.cat"
"E:\PartImage\Ethernet_drv\realtek\wlan\8187l\Netrtuw.inf"
"E:\PartImage\Ethernet_drv\realtek\wlan\8187l\Netrtuwo.inf"
"E:\PartImage\Ethernet_drv\realtek\wlan\8187l\rtl8187.sys"

.Set DestinationDir=".\sis"

.Set DestinationDir=".\sis\lan"
"E:\PartImage\Ethernet_drv\sis\lan\NETOEM.INF"
"E:\PartImage\Ethernet_drv\sis\lan\oemnic.cat"
"E:\PartImage\Ethernet_drv\sis\lan\readme.txt"
"E:\PartImage\Ethernet_drv\sis\lan\sisgbe.cat"
"E:\PartImage\Ethernet_drv\sis\lan\SiSGbe.inf"
"E:\PartImage\Ethernet_drv\sis\lan\SiSGbeXP.sys"
"E:\PartImage\Ethernet_drv\sis\lan\SISNICXP.sys"

.Set DestinationDir=".\sis\wlan"
"E:\PartImage\Ethernet_drv\sis\wlan\readme.txt"

.Set DestinationDir=".\sis\wlan\160"
"E:\PartImage\Ethernet_drv\sis\wlan\160\SIS160.CAT"
"E:\PartImage\Ethernet_drv\sis\wlan\160\SiS160.inf"
"E:\PartImage\Ethernet_drv\sis\wlan\160\SIS160.sys"
"E:\PartImage\Ethernet_drv\sis\wlan\160\Uninst2k.exe"

.Set DestinationDir=".\sis\wlan\162"
"E:\PartImage\Ethernet_drv\sis\wlan\162\SIS162.CAT"
"E:\PartImage\Ethernet_drv\sis\wlan\162\SiS162.inf"
"E:\PartImage\Ethernet_drv\sis\wlan\162\sis162.sys"
"E:\PartImage\Ethernet_drv\sis\wlan\162\sis162u.cat"
"E:\PartImage\Ethernet_drv\sis\wlan\162\sis162u.inf"
"E:\PartImage\Ethernet_drv\sis\wlan\162\sis162u.sys"
"E:\PartImage\Ethernet_drv\sis\wlan\162\SiSWBase.dll"
"E:\PartImage\Ethernet_drv\sis\wlan\162\SiSWInst.dll"
"E:\PartImage\Ethernet_drv\sis\wlan\162\SiSWPars.dll"
"E:\PartImage\Ethernet_drv\sis\wlan\162\Unwlsdrv.exe"

.Set DestinationDir=".\sis\wlan\163"
"E:\PartImage\Ethernet_drv\sis\wlan\163\SIS163.CAT"
"E:\PartImage\Ethernet_drv\sis\wlan\163\SiS163.inf"
"E:\PartImage\Ethernet_drv\sis\wlan\163\SiS163.sys"
"E:\PartImage\Ethernet_drv\sis\wlan\163\Unwlsdrv.exe"

.Set DestinationDir=".\sis\wlan\163\USB"
"E:\PartImage\Ethernet_drv\sis\wlan\163\USB\sis163u.cat"
"E:\PartImage\Ethernet_drv\sis\wlan\163\USB\sis163u.inf"
"E:\PartImage\Ethernet_drv\sis\wlan\163\USB\SiS163u.sys"
"E:\PartImage\Ethernet_drv\sis\wlan\163\USB\Unwlsdrv.exe"

.Set DestinationDir=".\tp-link"

.Set DestinationDir=".\tp-link\lan"
"E:\PartImage\Ethernet_drv\tp-link\lan\NetrtOEM.inf"
"E:\PartImage\Ethernet_drv\tp-link\lan\NETRTS5.INF"
"E:\PartImage\Ethernet_drv\tp-link\lan\readme.txt"
"E:\PartImage\Ethernet_drv\tp-link\lan\RTL8139.SYS"
"E:\PartImage\Ethernet_drv\tp-link\lan\Rtlnicxp.sys"

.Set DestinationDir=".\tp-link\wlan"
"E:\PartImage\Ethernet_drv\tp-link\wlan\11gAdapter.inf"
"E:\PartImage\Ethernet_drv\tp-link\wlan\11gAdapter.sys"
"E:\PartImage\Ethernet_drv\tp-link\wlan\ar5211.sys"
"E:\PartImage\Ethernet_drv\tp-link\wlan\ar5416.sys"
"E:\PartImage\Ethernet_drv\tp-link\wlan\arusb_xp.cat"
"E:\PartImage\Ethernet_drv\tp-link\wlan\arusb_xp.inf"
"E:\PartImage\Ethernet_drv\tp-link\wlan\arusb_xp.sys"
"E:\PartImage\Ethernet_drv\tp-link\wlan\athw.sys"
"E:\PartImage\Ethernet_drv\tp-link\wlan\net5211.cat"
"E:\PartImage\Ethernet_drv\tp-link\wlan\net5211.inf"
"E:\PartImage\Ethernet_drv\tp-link\wlan\net5416.inf"
"E:\PartImage\Ethernet_drv\tp-link\wlan\netathw.cat"
"E:\PartImage\Ethernet_drv\tp-link\wlan\netathw.inf"
"E:\PartImage\Ethernet_drv\tp-link\wlan\readme.txt"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXGEN.BIN"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXLN.CAT"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXLN.INF"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXLN.SYS"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXMX.BIN"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXRFM.BIN"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXRMX.BIN"
"E:\PartImage\Ethernet_drv\tp-link\wlan\TIACXSN.BIN"
"E:\PartImage\Ethernet_drv\tp-link\wlan\ZD11BUXP.SYS"
"E:\PartImage\Ethernet_drv\tp-link\wlan\ZD1211BU.CAT"
"E:\PartImage\Ethernet_drv\tp-link\wlan\ZD1211BU.INF"

.Set DestinationDir=".\uli"
"E:\PartImage\Ethernet_drv\uli\Netuli.inf"
"E:\PartImage\Ethernet_drv\uli\readme.txt"
"E:\PartImage\Ethernet_drv\uli\ulilan.cat"
"E:\PartImage\Ethernet_drv\uli\ulilan51.sys"

.Set DestinationDir=".\via"

.Set DestinationDir=".\via\lan"
"E:\PartImage\Ethernet_drv\via\lan\difxapi.dll"
"E:\PartImage\Ethernet_drv\via\lan\FETND5BV.sys"
"E:\PartImage\Ethernet_drv\via\lan\FETNDIS.inf"
"E:\PartImage\Ethernet_drv\via\lan\GETND5BV.sys"
"E:\PartImage\Ethernet_drv\via\lan\getndis.cat"
"E:\PartImage\Ethernet_drv\via\lan\getndis.inf"
"E:\PartImage\Ethernet_drv\via\lan\netvt.cat"
"E:\PartImage\Ethernet_drv\via\lan\readme.txt"
"E:\PartImage\Ethernet_drv\via\lan\vuins32.dll"

.Set DestinationDir=".\via\wlan"
"E:\PartImage\Ethernet_drv\via\wlan\readme.txt"
"E:\PartImage\Ethernet_drv\via\wlan\vntwnet.cat"
"E:\PartImage\Ethernet_drv\via\wlan\VNUWL.inf"
"E:\PartImage\Ethernet_drv\via\wlan\VNUWL5B.sys"
"E:\PartImage\Ethernet_drv\via\wlan\VNWL.inf"
"E:\PartImage\Ethernet_drv\via\wlan\VNWL5B.sys"
"E:\PartImage\Ethernet_drv\via\wlan\vuins32.dll"
